// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jcqdbiksqrcphzyxrlyl.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjcWRiaWtzcXJjcGh6eXhybHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE2NTcwNzUsImV4cCI6MjA0NzIzMzA3NX0.o4AmYt1R1uoXrQDHOX1B23DUt-dtk-epSY7R6XdRT_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);